### ISSUE TITLE
dbpedia 相关数据文件能否给出官方下载链接，而非百度网盘？

### ISSUE THREAD

**Issue by 0wave** [pkumod/gAnswer#10]
工作环境无法使用百度网盘，能否提供原始下载链接？ 谢谢～

**Comment by knightmarehs** [comment]
DBpedia原始数据集可以从[官网](https://wiki.dbpedia.org/develop/datasets/downloads-2016-10)下载，你可以自行将其处理成triples文件(格式：<s><p><o>.)和索引文件(格式参考代码)。

**Comment by 0wave** [comment]
了解了，感谢~
