### ISSUE TITLE
可以公布项目的数据集么？不知道怎么从DBpeedia中获取数据

### ISSUE THREAD

**Issue by yuanwenshu** [pkumod/gAnswer#15]

**Comment by knightmarehs** [comment]
You can find the download link of index data in [quick start](https://github.com/pkumod/gAnswer#quick-start).
Also you can find the raw DBpedia data (triple files) in [DBpedia](https://wiki.dbpedia.org/develop/datasets/dbpedia-version-2016-10).
We will upload our preprocessed triple file (can be used to build database by GStore) later.
