### ISSUE TITLE
我在源代码部署项目的时候发现外部jar包有问题

### ISSUE THREAD

**Issue by YangLingWHU** [pkumod/gAnswer#20]
问题：如果源代码eclipse部署的话，百度网盘下载的**外部jar**包是有问题的，回报classnotfound异常。servlet-api.jar 中缺少一些类。
我的修改方式：下载“Deploy GAnswer via jar”这一部分提供的 Ganswer.jar，从中提取出**servlet-api-3.0.jar**，替换掉**servlet-api.jar** 。

**Comment by knightmarehs** [comment]
谢谢，我们会尽快查看这个问题。

**Comment by YangLingWHU** [comment]
> master

master分支

**Comment by nicklin96** [comment]
您好！非常感谢您的反馈，我们已经重新上传了正确的jar包
