### ISSUE TITLE
在ganswer中文版上使用自己的数据

### ISSUE THREAD

**Issue by liyumeng2018** [pkumod/gAnswer#25]
您好，中文版没有src/lcn/BuildIndexForEntityFragments.java和src/lucene/BuildIndexForTypeShortName.java.这两个文件，如果想要将pkubase更换为自己的数据，是否可以直接用英文版的这两个文件?

**Comment by liyumeng2018** [comment]
已成功迁移数据，确实要用英文版的这两个文件。

**Comment by knightmarehs** [comment]
感谢你的反馈，是的，迁移数据重建索引还是用这两个文件。这段时间在忙着实习和面试，回复不及时敬请谅解。
