### ISSUE TITLE
你好，triples.txt数据集导入gStore报错

### ISSUE THREAD

**Issue by Adnios** [pkumod/gAnswer#26]
finish initial sub2id_pre2id_obj2id
begin build Prefix
lexer error in line 333505: invalid string
lexer error in line 3576854: invalid string
Killed
然后就中断了，请问这是什么原因

**Comment by Adnios** [comment]
已经解决了，是服务器配置低的缘故，换一台配置较高的即可了

**Comment by knightmarehs** [comment]
你好，谢谢你的反馈！
