### ISSUE TITLE
supplemental material可以在哪里找到？

### ISSUE THREAD

**Issue by YuanQing96** [pkumod/gAnswer#32]
你好，请问你们answering natural language questions by subgraph matching over knowledge graph这篇论文中提到的online supplemental material可以在哪里找到，我找了一圈没找到。

**Comment by knightmarehs** [comment]
We have uploaded the supplemental material now, you can find it in the docs directory or just click [here](https://github.com/pkumod/gAnswer/blob/master/docs/TKDE18_gAnswer_supplementary.pdf).

**Comment by YuanQing96** [comment]
感谢！
