### ISSUE TITLE
data/pkubase/paraphrase/mini-mention2ent.txt (没有那个文件或目录)

### ISSUE THREAD

**Issue by Traeyee** [pkumod/gAnswer#34]
关于pkubase的文件好像缺失，可不可以更新一下

**Comment by knightmarehs** [comment]
明天更新

发自我的 iPhone

**Comment by Traeyee** [comment]
expecting...thx

**Comment by Traeyee** [comment]
> 明天更新 发自我的 iPhone
> […](#)
> 在 2020年1月3日，下午9:59，Traeyee ***@***.***> 写道： 关于pkubase的文件好像缺失，可不可以更新一下 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

expecting... thx

**Comment by knightmarehs** [comment]
您好，针对您的问题，将报错部分的mini替换为pkubase即可，我们已经更新了代码，同时提供了非常小的知识库相关数据索引，以便大家在内存较小的本机上进行测试。
