### ISSUE TITLE
您好，我32g的内存也跑不起来

### ISSUE THREAD

**Issue by caoyuewen** [pkumod/gAnswer#4]
您好，我32g的内存也跑不起来

系统：Linux server 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

jdk版本：
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

使用命令：java -jar Ganswer.jar -XX:UseGCOverheadLimit -Xms20480m

报错信息： 
Loading entity fragments ...
Exception in thread "main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
Exception in thread "DateCache" java.lang.OutOfMemoryError: GC overhead limit exceeded

程序运行时候内存情况：
server@server:/usr/java$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        9.0G         11G        1.0M         10G         21G
Swap:          4.0G          0B        4.0G

未运行时内存情况：
server@server:/usr/java$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        703M         19G        1.0M         10G         30G
Swap:          4.0G          0B        4.0G

_Originally posted by @caoyuewen in https://github.com/pkumod/gAnswer/issues/3#issuecomment-457808047_

**Comment by knightmarehs** [comment]
你好，可以试一下
-Xmx20480m
