### ISSUE TITLE
http://ganswer.gstore-pku.com  does not work

### ISSUE THREAD

**Issue by jiguangxi** [pkumod/gAnswer#43]
Hello, sir.
I try to run some queries from http://ganswer.gstore-pku.com, but the URL does not open

**Comment by jiguangxi** [comment]
@knightmarehs  自己笔记本无法部署完整的gAnswer，而使用jar包版gAnswer又显示 http://dbpedia16.gstore-pku.com服务出错。如果有可能的话，麻烦您重启一下这个demo服务，谢谢。

**Comment by knightmarehs** [comment]
嗨，服务器这几天受到不明攻击，现在已经关了外网访问，会在处理好后再开放。如果是内存原因无法部署完整数据，可以使用小规模的数据。然后在本地部署gStore来代替dbpedia16.gstore-pku.com。

**Comment by jiguangxi** [comment]
哦哦    好的，感谢感谢
