### ISSUE TITLE
Cann't run it on windows10

### ISSUE THREAD

**Issue by Zhiyong-Tsang** [pkumod/gAnswer#55]
When I ran 'java -jar Ganswer.jar', I got the following error:

错误: 无法初始化主类 application.GanswerHttp
原因: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler

Please tell me how to fix it, Thank you in advance!

**Comment by Zhiyong-Tsang** [comment]
I knew how to fix it! But I came to another problem, when I ran the example by "HTTP", it threw an error: 
{"question":"Who is the wife of Donald Trump?","message":"InvalidQuestionException: the question you input is invalid, please check","status":"500"}
Would you help me out, and the help document is missing, I don't know where it is.

**Comment by nicklin96** [comment]
Try not using the question mark？

**Comment by Zhiyong-Tsang** [comment]
Let me try, thank you!
