### ISSUE TITLE
{"question":"Who is the wife of Donald Trump?","message":"InvalidQuestionException: the question you input is invalid, please check","status":"500"} 

### ISSUE THREAD

**Issue by niccip07** [pkumod/gAnswer#62]
I set up gAnswer as described in the readme. But with the sample question I get the response that the input is invalid.

{"question":"Who is the wife of Donald Trump?","message":"InvalidQuestionException: the question you input is invalid, please check","status":"500"} 

What to do?

**Comment by niccip07** [comment]
solved.

**Comment by haophancs** [comment]
Hi, could you please tell me how you solved it?
