### ISSUE TITLE
SparQL查询总是timeout

### ISSUE THREAD

**Issue by zhoujz10** [pkumod/gAnswer#8]
非常感谢开源你们的代码!
我把代码部署到本地之后,发现系统在生成SparQL语句之后,连接你们的图数据库总是timeout.
请问能否开放图数据库的数据,让我们部署到本地呢?谢谢~

**Comment by knightmarehs** [comment]
您好，非常推荐您在本地部署自己的数据库。
具体操作方法可参考readme中的[注意事项](https://github.com/pkumod/gAnswer/blob/master/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)。

**Comment by zhoujz10** [comment]
非常感谢！
